// Package studio owns the Studio mode contracts and bounded result collector
// for NextSQL Admin (Phase 29). The HTTP/session adapter lives in the sibling
// ops package for now because the first Studio increment deliberately reuses
// the operator's already-authenticated NSQL connection. Studio still reaches
// nextsqld only through the official Go driver; it never reads storage, WAL,
// catalog, or key files directly.
package studio

import (
	"context"
	"fmt"
	"regexp"
	"strings"
	"time"
	"unicode"

	"github.com/bzync/nextsql/internal/nerr"
	"github.com/bzync/nextsql/internal/sql/ast"
	"github.com/bzync/nextsql/internal/sql/lexer"
	"github.com/bzync/nextsql/internal/sql/parser"
	"github.com/bzync/nextsql/internal/sql/types"
)

const (
	// MaxSQLBytes is below the NSQL protocol's own SQL ceiling and bounds the
	// browser-to-Admin request before it is decoded or sent to nextsqld.
	MaxSQLBytes = 1 << 20
	// MaxResultRows and MaxResultBytes bound both the legacy M1 materialized
	// preview and M2's streaming browser preview.
	MaxResultRows  = 5_000
	MaxResultBytes = 8 << 20
	// StreamBatchRows and StreamBatchBytes keep each browser-facing NDJSON
	// frame bounded while avoiding one HTTP flush and one React update per
	// result row. A single row may exceed StreamBatchBytes, but can never
	// exceed StreamRowBytes; it is emitted alone in that case.
	StreamBatchRows  = 128
	StreamBatchBytes = 256 << 10
	// StreamRowBytes prevents JSON escaping of one adversarial row from
	// turning the 8 MiB aggregate preview budget into a very large single
	// HTTP frame. The result is explicitly truncated before such a row is
	// retained or emitted.
	StreamRowBytes = 1 << 20
	// MaxTables bounds the initial explorer listing. Column and index detail
	// is fetched only when one of these tables is selected.
	MaxTables = 1_000
	// MaxScriptStatements bounds one Execute Script request. Each statement
	// still runs sequentially through the same one-active-query-per-session
	// path as a single statement, so this only bounds how large a single
	// script submission can be, not query concurrency.
	MaxScriptStatements = 200

	// Leave five seconds inside Admin's 30-second HTTP write deadline so a
	// timeout can be canceled, drained, and returned as a structured error.
	QueryTimeout = 25 * time.Second
)

const StreamContentType = "application/x-ndjson"

var queryIDPattern = regexp.MustCompile(`^[A-Za-z0-9_-]{1,128}$`)

// MaxQueryParams bounds one parameterized editor run. NextSQL binds
// positional parameters ($1..$N); the editor sends one slot per referenced
// position, so this also bounds how many placeholders a single run may use.
const MaxQueryParams = 32

// MaxQueryParamBytes bounds one bound value. Values travel as strings and are
// coerced server-side against the statement's expected parameter type — the
// same untyped-string binding path the drivers already rely on — so a value
// larger than this is rejected before it reaches the connection.
const MaxQueryParamBytes = 64 << 10

// QueryParam is one positional bind value for a parameterized editor
// statement. Value is nil for a SQL NULL; otherwise it is a string the server
// coerces to the parameter's expected type. $1 is params[0].
type QueryParam struct {
	Value *string `json:"value"`
}

// QueryRequest is supplied by the editor. QueryID is generated by the
// browser before execution so a concurrent cancellation request can name the
// in-flight query without waiting for the query response. Params, when
// present, are positional bind values for the statement's $1..$N.
type QueryRequest struct {
	QueryID string       `json:"query_id"`
	SQL     string       `json:"sql"`
	Params  []QueryParam `json:"params,omitempty"`
}

// CancelRequest identifies one in-flight query owned by the current Admin
// session. It can never cancel another browser session's connection.
type CancelRequest struct {
	QueryID string `json:"query_id"`
}

// ResultSet is the wire-neutral result shape used by Studio. Cells are
// rendered from the official driver's typed values, with NULL kept distinct.
type ResultSet struct {
	Columns     []string    `json:"columns"`
	ColumnTypes []string    `json:"column_types"`
	Rows        [][]*string `json:"rows"`
	Affected    int64       `json:"affected,omitempty"`
	Truncated   bool        `json:"truncated"`
	ElapsedMS   int64       `json:"elapsed_ms"`
}

// StreamFrame is one bounded NDJSON record on the Studio streaming query
// response. The order is always meta, zero or more rows frames, then
// complete. The HTTP adapter may append an error frame instead of complete
// when iteration fails after the response has started.
type StreamFrame struct {
	Type        string      `json:"type"`
	Columns     []string    `json:"columns,omitempty"`
	ColumnTypes []string    `json:"column_types,omitempty"`
	Rows        [][]*string `json:"rows,omitempty"`
	Affected    int64       `json:"affected,omitempty"`
	Truncated   bool        `json:"truncated,omitempty"`
	ElapsedMS   int64       `json:"elapsed_ms,omitempty"`
	RowCount    int         `json:"row_count,omitempty"`
	Error       string      `json:"error,omitempty"`
	ErrorCode   string      `json:"error_code,omitempty"`
}

// Bootstrap is the capability-aware, bounded first read for the Studio
// workspace. Tables are listed here; their columns/indexes are lazy-loaded.
// ServerAddr is the host:port of the nextsqld the running nextsql-admin
// process targets — display only, so the workspace can show which server the
// authenticated session is talking to. It is fixed for the process; the
// realm and database within it are switchable via the reconnect route.
type Bootstrap struct {
	GeneratedAt     string    `json:"generated_at"`
	ServerAddr      string    `json:"server_addr"`
	ReadConsistency string    `json:"read_consistency"`
	MaxStalenessMS  int64     `json:"max_staleness_ms"`
	Capabilities    ResultSet `json:"capabilities"`
	Tables          ResultSet `json:"tables"`
	TablesTruncated bool      `json:"tables_truncated"`
	Warnings        []string  `json:"warnings,omitempty"`
}

// Read-consistency modes as they travel on the Studio wire. They map 1:1 to
// the official driver's ReadConsistency (Strong/Bounded/Stale) and to
// nextsqld's own executor.ReadConsistency ordering.
const (
	ReadStrong  = "strong"
	ReadBounded = "bounded"
	ReadStale   = "stale"
)

// MaxReadStalenessMS caps the BOUNDED freshness bound a Studio session may
// request. Real staleness bounds are single-digit seconds; this hard ceiling
// (one hour) only stops a nonsense value from reaching nextsqld.
const MaxReadStalenessMS = 60 * 60 * 1000

// SetReadConsistencyRequest changes how the current Studio session's reads
// observe replicated state. It is a live session-control message on the
// existing connection — no reconnect, no new credential. MaxStalenessMS is
// only meaningful for BOUNDED (0 selects the server default).
type SetReadConsistencyRequest struct {
	Mode           string `json:"mode"`
	MaxStalenessMS int64  `json:"max_staleness_ms"`
}

// Validate shape-checks a read-consistency change before it reaches the
// connection. Only the three known modes are accepted; a staleness bound is
// non-negative and under MaxReadStalenessMS.
func (r SetReadConsistencyRequest) Validate() error {
	switch r.Mode {
	case ReadStrong, ReadBounded, ReadStale:
	default:
		return nerr.New(nerr.InvalidArgument, "studio.SetReadConsistencyRequest",
			"read consistency must be strong, bounded, or stale")
	}
	if r.MaxStalenessMS < 0 || r.MaxStalenessMS > MaxReadStalenessMS {
		return nerr.New(nerr.InvalidArgument, "studio.SetReadConsistencyRequest",
			fmt.Sprintf("max_staleness_ms must be between 0 and %d", MaxReadStalenessMS))
	}
	return nil
}

// ReadConsistencyState is the current session read-consistency, echoed back
// after a successful change and included in the bootstrap read.
type ReadConsistencyState struct {
	Mode           string `json:"mode"`
	MaxStalenessMS int64  `json:"max_staleness_ms"`
}

// MaxConnNameBytes bounds a realm or database name on the reconnect route
// before it is sent to nextsqld. NextSQL realm/database names are bare
// identifiers well under this; the cap is a hard backstop on the browser
// request, not an expected ceiling.
const MaxConnNameBytes = 128

// connNamePattern is the exact shape a non-empty realm or database name may
// take on the reconnect route: the bare-identifier characters NextSQL's
// Hello accepts. An empty string is allowed (it selects the deployment
// default), so the pattern is only applied to a non-empty value.
var connNamePattern = regexp.MustCompile(`^[A-Za-z0-9_-]{1,128}$`)

// ReconnectRequest re-targets the current Studio session's connection to a
// different realm and/or database on the same nextsqld, as the same NSQL
// user. The password is required because NextSQL binds realm/database at
// handshake time only — a switch needs a fresh authenticated connection —
// and Studio persists no credential of its own. The password is used once to
// open the new connection and is never stored.
type ReconnectRequest struct {
	Realm    string `json:"realm"`
	Database string `json:"database"`
	Password string `json:"password"`
}

// Validate bounds and shape-checks a reconnect request before any network
// I/O. It does not check that the realm/database exist or that the password
// is correct — nextsqld remains the sole authority over that.
func (r ReconnectRequest) Validate() error {
	if r.Password == "" {
		return nerr.New(nerr.InvalidArgument, "studio.ReconnectRequest", "password is required to switch connection")
	}
	if len(r.Realm) > MaxConnNameBytes || len(r.Database) > MaxConnNameBytes {
		return nerr.New(nerr.InvalidArgument, "studio.ReconnectRequest",
			fmt.Sprintf("realm and database names may be at most %d bytes", MaxConnNameBytes))
	}
	if r.Realm != "" && !connNamePattern.MatchString(r.Realm) {
		return nerr.New(nerr.InvalidArgument, "studio.ReconnectRequest", "realm name is not a valid identifier")
	}
	if r.Database != "" && !connNamePattern.MatchString(r.Database) {
		return nerr.New(nerr.InvalidArgument, "studio.ReconnectRequest", "database name is not a valid identifier")
	}
	return nil
}

// Connection is the current Studio session's connection identity returned by
// a successful reconnect: the NSQL user (unchanged), and the now-active realm
// and database. It carries no credential and no CSRF token — the session id
// and its CSRF token are unchanged by a reconnect.
type Connection struct {
	User     string `json:"user"`
	Realm    string `json:"realm"`
	Database string `json:"database"`
}

// TableDetail is the authorized server metadata for one selected table.
// ForeignKeys (this table's own FK constraints), ReferencingKeys (FK
// constraints on other visible tables that point at this one), Triggers
// (row triggers defined on this table), TableStats, IndexStats and DDL share
// system.tables' table-visibility filter and are list-shaped: an empty result
// means the table has no such rows yet, not an error. DDL is system.table_ddl
// rows for this table (the canonical CREATE statements) and Triggers is
// system.triggers rows for this table; neither is required — a server without
// that view degrades to no panel rather than a failed detail load.
type TableDetail struct {
	GeneratedAt     string    `json:"generated_at"`
	Name            string    `json:"name"`
	Table           ResultSet `json:"table"`
	Columns         ResultSet `json:"columns"`
	Indexes         ResultSet `json:"indexes"`
	ForeignKeys     ResultSet `json:"foreign_keys"`
	ReferencingKeys ResultSet `json:"referencing_keys"`
	Triggers        ResultSet `json:"triggers"`
	TableStats      ResultSet `json:"table_stats"`
	IndexStats      ResultSet `json:"index_stats"`
	DDL             ResultSet `json:"ddl"`
	Warnings        []string  `json:"warnings,omitempty"`
}

// WorkflowOverviewMaxRows bounds every result set in the workflow explorer.
// The relationship diagram applies a much smaller legibility bound, while
// these result tables retain enough rows for useful inspection without ever
// materializing an unbounded definition or activity catalog in the browser.
const WorkflowOverviewMaxRows = 500

// WorkflowOverview is the authorized read-only catalog for the Studio
// Workflows, triggers, schedules, tasks & change streams explorer. Every
// result set carries the system catalog's own RBAC filtering. Triggers,
// Schedules, Tasks and ChangeStreams are list-shaped and legitimately empty
// when none exist or none are visible.
type WorkflowOverview struct {
	GeneratedAt   string    `json:"generated_at"`
	Workflows     ResultSet `json:"workflows"`
	Triggers      ResultSet `json:"triggers"`
	Schedules     ResultSet `json:"schedules"`
	Tasks         ResultSet `json:"tasks"`
	ChangeStreams ResultSet `json:"change_streams"`
	Warnings      []string  `json:"warnings,omitempty"`
}

// SchemaGraphMaxRows bounds the schema-graph foreign-key read. A schema at
// the 1,000-table bootstrap cap with the per-table maximum of 16 foreign keys
// is far below this; the limit is a hard backstop, not an expected ceiling.
const SchemaGraphMaxRows = 4000

// SchemaGraph is the authorized read-only foreign-key catalog for the Studio
// schema-relationship diagram: every visible `system.foreign_keys` row, one
// per referencing column, carrying the system catalog's own RBAC filtering (a
// row is visible only when the caller can SELECT its child table). Truncated
// is set when the read hit SchemaGraphMaxRows.
type SchemaGraph struct {
	GeneratedAt string    `json:"generated_at"`
	ForeignKeys ResultSet `json:"foreign_keys"`
	Truncated   bool      `json:"truncated"`
	Warnings    []string  `json:"warnings,omitempty"`
}

// MigrationHistoryMaxRows bounds the schema-migration history read. A project
// with more applied migrations than this is well beyond any realistic schema
// lifecycle; the cap is a hard backstop, not an expected ceiling.
const MigrationHistoryMaxRows = 2000

// MigrationHistory is the authorized read-only view of a database's
// `nsql_schema_migrations` table for the Studio migration explorer. It adds no
// server capability: the same SELECT any editor statement could run through the
// logged-in operator's own NSQL connection. History is a reserved user table,
// not a `system.*` view, so the authority here is the caller's own SELECT
// privilege on it. Present is false when the table does not exist (the official
// migration system has never run on this database) or the caller cannot see it;
// the reason is in Warnings. Authoring, validating and applying migrations
// stays with the `nextsql migrate` CLI, which needs the local migration files
// this protocol-only client never holds.
type MigrationHistory struct {
	GeneratedAt string    `json:"generated_at"`
	Present     bool      `json:"present"`
	History     ResultSet `json:"history"`
	Truncated   bool      `json:"truncated"`
	Warnings    []string  `json:"warnings,omitempty"`
}

// RowStream is the subset of the official Go driver's Rows used by the
// collector. Keeping it as an interface makes the memory-bound behavior
// directly unit-testable without a database or a private engine API.
type RowStream interface {
	Columns() []string
	ColumnTypes() []types.Type
	Next() bool
	Values() []types.Value
	Err() error
	Affected() int64
	Close() error
}

func ValidateQueryID(id string) error {
	if !queryIDPattern.MatchString(id) {
		return nerr.New(nerr.InvalidArgument, "studio.ValidateQueryID",
			"query_id must contain 1-128 letters, digits, underscores, or hyphens")
	}
	return nil
}

// AnalyzeRequest is the editor's pre-execution safety-check request. It
// never executes the statement or opens a driver connection.
type AnalyzeRequest struct {
	SQL string `json:"sql"`
}

// Analysis is the SQL editor's pre-execution safety classification for one
// statement, computed by parsing it with the same grammar nextsqld's own
// executor uses. It is advisory only: the server remains the sole authority
// over whether the statement is valid, authorized, or has any actual effect.
type Analysis struct {
	Kind        string   `json:"kind"`
	Destructive bool     `json:"destructive"`
	Reasons     []string `json:"reasons,omitempty"`
	// Write is true when this statement mutates data, schema, catalog,
	// server config, or transaction state — the same DML/DDL/transaction
	// classification nextsqld's own executor.isMutating uses, plus the
	// operational writes (SET CONFIG, BACKUP, cluster ops). The editor's
	// read-only production safety mode blocks a Write statement unless the
	// user explicitly overrides it; it is advisory, never a substitute for
	// server-side RBAC.
	Write bool `json:"write"`
	// RealmScoped is true for a statement that changes the realm-wide
	// principal namespace — CREATE/DROP USER, CREATE/DROP ROLE. NextSQL
	// identities are defined once per realm ("realm identities and roles
	// with database-scoped grants", docs/design-multidatabase-dbaas.md §19),
	// so the effect reaches every database in the connected realm, not just
	// the one the Studio session is pointed at. The confirm-before-run
	// dialog names the realm so a cross-database change is never silent.
	// Advisory only, exactly like Destructive/Write.
	RealmScoped bool `json:"realm_scoped,omitempty"`
}

// Analyze classifies one editor statement for a confirm-before-run warning.
// It parses sql with internal/sql/parser — the same package the executor
// binds and runs — and never opens a database connection. A parse failure is
// reported so the caller can choose to skip the warning rather than block a
// query the real executor would still accept or reject on its own terms.
func Analyze(sql string) (Analysis, error) {
	if err := ValidateSQL(sql); err != nil {
		return Analysis{}, err
	}
	stmt, err := parser.Parse(sql)
	if err != nil {
		return Analysis{}, nerr.Wrap(nerr.Syntax, "studio.Analyze", "SQL could not be parsed", err)
	}
	a := classify(stmt)
	a.Write = isWriteStmt(stmt)
	a.RealmScoped = isRealmScopedStmt(stmt)
	return a, nil
}

// isRealmScopedStmt reports whether the statement mutates the realm-wide
// principal namespace that every database in the realm shares. GRANT/REVOKE
// are deliberately excluded: a NextSQL grant carries a DatabaseID and can be
// database-scoped, and the GRANT/REVOKE builder already shows the operator
// the exact object and scope. CREATE/DROP USER and CREATE/DROP ROLE have no
// such scoping — the identity exists once for the whole realm, so running one
// against the wrong Studio connection changes access for databases the
// operator never opened.
func isRealmScopedStmt(stmt ast.Stmt) bool {
	switch stmt.(type) {
	case ast.CreateUser, ast.DropUser, ast.CreateRole, ast.DropRole:
		return true
	default:
		return false
	}
}

// isWriteStmt mirrors nextsqld's executor.isMutating (DML / DDL / workflow /
// trigger / schedule / resource-group / index DDL / transaction control) at
// the AST level — Studio has no bound plan to inspect — and additionally
// counts the operational writes the executor gates elsewhere (SET CONFIG,
// BACKUP DATABASE, MAINTAIN, and the cluster control statements). Anything
// not listed here (SELECT, SHOW, SUBSCRIBE, ANALYZE, EXPLAIN, VERIFY BACKUP,
// RESET/SET RESOURCE GROUP) is treated as a read for the read-only safety
// mode. EXPLAIN is deliberately a read even though EXPLAIN ANALYZE of a
// write does execute it — the safety mode is advisory and the confirm
// dialog still covers a destructive inner statement.
func isWriteStmt(stmt ast.Stmt) bool {
	switch stmt.(type) {
	case ast.Insert, ast.Upsert, ast.Update, ast.Delete,
		ast.CreateTable, ast.CreateDatabase, ast.DropTable, ast.AlterTable,
		ast.CreateIndex, ast.DropIndex, ast.RebuildIndex,
		ast.CreateWorkflow, ast.AlterWorkflow, ast.DropWorkflow, ast.RunWorkflow,
		ast.CreateTrigger, ast.AlterTrigger, ast.DropTrigger,
		ast.CreateSchedule, ast.AlterSchedule, ast.DropSchedule,
		ast.CreateResourceGroup, ast.AlterResourceGroup, ast.DropResourceGroup,
		ast.CancelTask,
		ast.CreateUser, ast.DropUser, ast.CreateRole, ast.DropRole, ast.Grant, ast.Revoke,
		ast.Begin, ast.Commit, ast.Rollback,
		ast.SetConfig, ast.BackupDatabase, ast.Maintain,
		ast.TransferLeader, ast.ClusterDrain, ast.ClusterMaintenance, ast.ClusterReconcileConfirm:
		return true
	default:
		return false
	}
}

func classify(stmt ast.Stmt) Analysis {
	switch s := stmt.(type) {
	case ast.Update:
		a := Analysis{Kind: "UPDATE"}
		if s.Where == nil {
			a.Destructive = true
			a.Reasons = append(a.Reasons, fmt.Sprintf(
				"No WHERE clause: this UPDATE modifies every row in %s.", s.Table))
		}
		return a
	case ast.Delete:
		a := Analysis{Kind: "DELETE"}
		if s.Where == nil {
			a.Destructive = true
			a.Reasons = append(a.Reasons, fmt.Sprintf(
				"No WHERE clause: this DELETE removes every row from %s.", s.Table))
		}
		return a
	case ast.DropTable:
		return destructive("DROP TABLE", fmt.Sprintf("Permanently drops table %s and all of its data.", s.Name))
	case ast.DropIndex:
		return destructive("DROP INDEX", fmt.Sprintf("Permanently drops index %s.", s.Name))
	case ast.DropUser:
		return destructive("DROP USER", fmt.Sprintf("Permanently removes login %s.", s.Name))
	case ast.DropRole:
		return destructive("DROP ROLE", fmt.Sprintf("Permanently removes role %s.", s.Name))
	case ast.DropWorkflow:
		return destructive("DROP WORKFLOW", fmt.Sprintf("Permanently removes workflow %s.", s.Name))
	case ast.DropTrigger:
		return destructive("DROP TRIGGER", fmt.Sprintf("Permanently removes trigger %s.", s.Name))
	case ast.DropSchedule:
		return destructive("DROP SCHEDULE", fmt.Sprintf("Permanently removes schedule %s.", s.Name))
	case ast.DropResourceGroup:
		return destructive("DROP RESOURCE GROUP", fmt.Sprintf("Permanently removes resource group %s.", s.Name))
	case ast.AlterTable:
		return classifyAlterTable(s)
	default:
		return Analysis{Kind: statementKind(stmt)}
	}
}

func classifyAlterTable(s ast.AlterTable) Analysis {
	a := Analysis{Kind: "ALTER TABLE"}
	switch cmd := s.Cmd.(type) {
	case ast.AlterDropColumn:
		a.Destructive = true
		a.Reasons = append(a.Reasons, fmt.Sprintf(
			"Permanently drops column %s and its stored data from %s.", cmd.Name, s.Table))
	case ast.AlterDropPartition:
		a.Destructive = true
		a.Reasons = append(a.Reasons, fmt.Sprintf(
			"Permanently drops partition %s and its rows from %s.", cmd.Name, s.Table))
	}
	return a
}

func destructive(kind, reason string) Analysis {
	return Analysis{Kind: kind, Destructive: true, Reasons: []string{reason}}
}

// statementKind names a non-destructive statement for display; it is never
// consulted for the destructive/reasons decision above.
func statementKind(stmt ast.Stmt) string {
	name := fmt.Sprintf("%T", stmt)
	if i := strings.LastIndex(name, "."); i >= 0 {
		name = name[i+1:]
	}
	return name
}

// Script is the ordered list of statements a script buffer splits into.
type Script struct {
	Statements []string `json:"statements"`
}

// SplitScript cuts one editor buffer into individually-runnable statements
// for Execute Script. It uses a real lexer pass — the same tokenizer the
// parser itself runs on — so a ';' inside a string, quoted identifier, or
// comment never cuts a statement early; comment-only and empty fragments are
// dropped. This deliberately re-implements internal/migrate.Split's
// three-line splitting loop rather than importing that package: migrate
// transitively pulls in internal/catalog, internal/security, and
// internal/cli, none of which belong in Studio's official-interfaces-only
// dependency footprint (see imports_test.go).
func SplitScript(sql string) ([]string, error) {
	if err := ValidateSQL(sql); err != nil {
		return nil, err
	}
	stmts, err := splitStatements(sql)
	if err != nil {
		return nil, nerr.Wrap(nerr.Syntax, "studio.SplitScript", "script could not be tokenized", err)
	}
	if len(stmts) == 0 {
		return nil, nerr.New(nerr.InvalidArgument, "studio.SplitScript", "script contains no statements")
	}
	if len(stmts) > MaxScriptStatements {
		return nil, nerr.New(nerr.Exhausted, "studio.SplitScript",
			fmt.Sprintf("script exceeds the %d-statement Studio limit", MaxScriptStatements))
	}
	return stmts, nil
}

func splitStatements(src string) ([]string, error) {
	lx := lexer.New(src)
	var stmts []string
	start := 0
	for {
		tok := lx.Next()
		if err := lx.Err(); err != nil {
			return nil, err
		}
		if tok.Kind != lexer.Semi && tok.Kind != lexer.EOF {
			continue
		}
		frag := strings.TrimSpace(src[start:tok.Pos])
		if frag != "" && !isBlankFragment(frag) {
			stmts = append(stmts, frag)
		}
		if tok.Kind == lexer.EOF {
			return stmts, nil
		}
		start = tok.Pos + len(tok.Lit)
	}
}

// isBlankFragment reports whether frag lexes to nothing but a comment (the
// lexer discards comments entirely, so such a fragment tokenizes straight to
// EOF).
func isBlankFragment(frag string) bool {
	lx := lexer.New(frag)
	tok := lx.Next()
	return tok.Kind == lexer.EOF && lx.Err() == nil
}

// stmtSpan is the byte range of one non-blank statement fragment within an
// editor buffer, whitespace already trimmed on both sides — start/end index
// the same string splitStatementSpans was given.
type stmtSpan struct{ start, end int }

// splitStatementSpans is splitStatements with the buffer offsets kept, so a
// per-statement parse diagnostic can be mapped back to the whole buffer. It
// applies the identical ';'-in-string/comment-safe lexer pass and the same
// blank/comment-only fragment filter.
func splitStatementSpans(src string) ([]stmtSpan, error) {
	lx := lexer.New(src)
	var spans []stmtSpan
	start := 0
	for {
		tok := lx.Next()
		if err := lx.Err(); err != nil {
			return nil, err
		}
		if tok.Kind != lexer.Semi && tok.Kind != lexer.EOF {
			continue
		}
		raw := src[start:tok.Pos]
		frag := strings.TrimSpace(raw)
		if frag != "" && !isBlankFragment(frag) {
			lead := start + (len(raw) - len(strings.TrimLeftFunc(raw, unicode.IsSpace)))
			spans = append(spans, stmtSpan{start: lead, end: lead + len(frag)})
		}
		if tok.Kind == lexer.EOF {
			return spans, nil
		}
		start = tok.Pos + len(tok.Lit)
	}
}

// Diagnostic locates a parse failure in one editor buffer, in the coordinates
// the browser textarea uses: Offset counts UTF-16 code units from the start
// of the buffer; Line and Column are 1-based, Column also in UTF-16 code
// units within its line. Message carries no "nextsql syntax:" prefix.
//
// It is advisory. nextsqld's parser/binder stay the sole authority on whether
// a statement is valid, and this covers grammar errors only — an unresolved
// table or column name is reported by the server when the statement actually
// runs, not here (Studio has no catalog of its own to resolve against).
type Diagnostic struct {
	Message string `json:"message"`
	Offset  int    `json:"offset"`
	Line    int    `json:"line"`
	Column  int    `json:"column"`
}

// DiagnosticReport is the editor's live parse-diagnostics response: one entry
// per statement in the buffer that does not parse, in buffer order. Empty
// when the whole buffer parses.
type DiagnosticReport struct {
	Diagnostics []Diagnostic `json:"diagnostics"`
}

// Diagnostics parses every statement in one editor buffer with the same
// grammar the executor uses and returns one location per statement that fails
// to parse (the parser stops at its first error, so never more than one per
// statement). A fully valid buffer returns an empty slice. It opens no driver
// connection and touches no query slot.
//
// An empty or oversized buffer is a request error, matching Analyze. A buffer
// that will not tokenize at all is reported as a single diagnostic at the
// lexer's stopping point rather than an error, so the editor can still point
// the operator at it.
func Diagnostics(sql string) ([]Diagnostic, error) {
	if err := ValidateSQL(sql); err != nil {
		return nil, err
	}
	spans, err := splitStatementSpans(sql)
	if err != nil {
		if _, diag, perr := parser.ParseDiag(sql); perr != nil && diag != nil {
			return []Diagnostic{locateInBuffer(sql, diag.Offset, diag.Message)}, nil
		}
		return nil, nerr.Wrap(nerr.Syntax, "studio.Diagnostics", "script could not be tokenized", err)
	}
	if len(spans) > MaxScriptStatements {
		return nil, nerr.New(nerr.Exhausted, "studio.Diagnostics",
			fmt.Sprintf("script exceeds the %d-statement Studio limit", MaxScriptStatements))
	}
	out := make([]Diagnostic, 0, len(spans))
	for _, sp := range spans {
		frag := sql[sp.start:sp.end]
		_, diag, perr := parser.ParseDiag(frag)
		if perr == nil || diag == nil {
			continue
		}
		off := diag.Offset
		if off < 0 {
			off = 0
		}
		if off > len(frag) {
			off = len(frag)
		}
		out = append(out, locateInBuffer(sql, sp.start+off, diag.Message))
	}
	return out, nil
}

// locateInBuffer converts a byte offset into src to the browser textarea's
// coordinates: a UTF-16 code-unit offset from the buffer start plus a 1-based
// line and (UTF-16) column.
func locateInBuffer(src string, byteOff int, msg string) Diagnostic {
	if byteOff < 0 {
		byteOff = 0
	}
	if byteOff > len(src) {
		byteOff = len(src)
	}
	prefix := src[:byteOff]
	line := 1 + strings.Count(prefix, "\n")
	col := 1 + utf16Len(prefix)
	if i := strings.LastIndexByte(prefix, '\n'); i >= 0 {
		col = 1 + utf16Len(prefix[i+1:])
	}
	return Diagnostic{Message: msg, Offset: utf16Len(prefix), Line: line, Column: col}
}

// utf16Len counts the UTF-16 code units s encodes to (JS string length), so a
// diagnostic offset lands on the right character in the editor even when the
// buffer contains astral-plane runes.
func utf16Len(s string) int {
	n := 0
	for _, r := range s {
		if r > 0xFFFF {
			n += 2
		} else {
			n++
		}
	}
	return n
}

func ValidateSQL(sql string) error {
	if strings.TrimSpace(sql) == "" {
		return nerr.New(nerr.InvalidArgument, "studio.ValidateSQL", "SQL is required")
	}
	if len(sql) > MaxSQLBytes {
		return nerr.New(nerr.Exhausted, "studio.ValidateSQL", "SQL exceeds the 1 MiB Studio limit")
	}
	return nil
}

// ValidateParams bounds a parameterized run: at most MaxQueryParams positional
// values, each at most MaxQueryParamBytes when present. A NULL bind (nil
// Value) has no size.
func ValidateParams(params []QueryParam) error {
	if len(params) > MaxQueryParams {
		return nerr.New(nerr.Exhausted, "studio.ValidateParams",
			fmt.Sprintf("a statement may bind at most %d parameters", MaxQueryParams))
	}
	for _, p := range params {
		if p.Value != nil && len(*p.Value) > MaxQueryParamBytes {
			return nerr.New(nerr.Exhausted, "studio.ValidateParams",
				fmt.Sprintf("a bound parameter value may be at most %d bytes", MaxQueryParamBytes))
		}
	}
	return nil
}

// ParamValues converts editor bind slots to positional driver values. A nil
// slot is a typed SQL NULL; a present slot is bound as a string and coerced
// server-side against the statement's expected parameter type.
func ParamValues(params []QueryParam) []types.Value {
	if len(params) == 0 {
		return nil
	}
	out := make([]types.Value, len(params))
	for i, p := range params {
		if p.Value == nil {
			out[i] = types.Null(types.NullType())
			continue
		}
		out[i] = types.StringValue(*p.Value)
	}
	return out
}

// Collect preserves the bounded M1 JSON endpoint for compatibility and tests.
// On the first row or byte beyond the preview limit it cancels the
// server query and drains/closes the driver Rows so the connection returns to
// a valid protocol frame boundary. Errors produced by that intentional
// cancellation are not reported as query failures; Truncated tells the user
// exactly what happened.
func Collect(ctx context.Context, rows RowStream, cancel context.CancelFunc) (ResultSet, error) {
	if rows == nil {
		return ResultSet{}, nerr.New(nerr.Internal, "studio.Collect", "nil row stream")
	}
	out := ResultSet{
		Columns:     rows.Columns(),
		ColumnTypes: typeNames(rows.ColumnTypes()),
		Rows:        [][]*string{},
	}
	used := resultMetadataBytes(out)

	for rows.Next() {
		if err := ctx.Err(); err != nil {
			_ = rows.Close()
			return ResultSet{}, nerr.Wrap(nerr.Canceled, "studio.Collect", "query canceled", err)
		}
		if len(out.Rows) >= MaxResultRows {
			out.Truncated = true
			cancel()
			_ = rows.Close()
			return out, nil
		}

		vals := rows.Values()
		if len(vals) != len(out.Columns) {
			cancel()
			_ = rows.Close()
			return ResultSet{}, nerr.New(nerr.InvalidFormat, "studio.Collect", "row width does not match result columns")
		}
		rec := make([]*string, len(vals))
		rowBytes := 0
		for i, v := range vals {
			if v.Null {
				continue
			}
			str := v.String()
			rowBytes += len(str)
			if used+rowBytes > MaxResultBytes {
				out.Truncated = true
				cancel()
				_ = rows.Close()
				return out, nil
			}
			rec[i] = &str
		}
		used += rowBytes
		out.Rows = append(out.Rows, rec)
	}
	if err := rows.Err(); err != nil {
		_ = rows.Close()
		return ResultSet{}, err
	}
	out.Affected = rows.Affected()
	if err := rows.Close(); err != nil {
		return ResultSet{}, err
	}
	return out, nil
}

// Stream converts a driver RowStream into bounded batches without
// materializing the full result. emit must consume each frame synchronously;
// Stream reuses no frame slices after emit returns. Cancellation, byte/row
// limits, iterator errors, and emitter failures all close the driver stream
// so its connection returns to a valid protocol boundary.
func Stream(ctx context.Context, rows RowStream, cancel context.CancelFunc, emit func(StreamFrame) error) error {
	if rows == nil {
		return nerr.New(nerr.Internal, "studio.Stream", "nil row stream")
	}
	if cancel == nil {
		return nerr.New(nerr.InvalidArgument, "studio.Stream", "nil cancel function")
	}
	if emit == nil {
		return nerr.New(nerr.InvalidArgument, "studio.Stream", "nil emitter")
	}

	started := time.Now()
	closed := false
	closeRows := func() error {
		if closed {
			return nil
		}
		closed = true
		return rows.Close()
	}
	defer func() { _ = closeRows() }()

	columns := rows.Columns()
	columnTypes := typeNames(rows.ColumnTypes())
	if err := emit(StreamFrame{Type: "meta", Columns: columns, ColumnTypes: columnTypes}); err != nil {
		cancel()
		return nerr.Wrap(nerr.IO, "studio.Stream", "emit metadata", err)
	}

	used := resultMetadataBytes(ResultSet{Columns: columns, ColumnTypes: columnTypes})
	rowCount := 0
	batchBytes := 0
	batch := make([][]*string, 0, StreamBatchRows)
	flush := func() error {
		if len(batch) == 0 {
			return nil
		}
		out := batch
		batch = make([][]*string, 0, StreamBatchRows)
		batchBytes = 0
		if err := emit(StreamFrame{Type: "rows", Rows: out}); err != nil {
			cancel()
			return nerr.Wrap(nerr.IO, "studio.Stream", "emit rows", err)
		}
		return nil
	}
	complete := func(truncated bool) error {
		if err := flush(); err != nil {
			return err
		}
		return emit(StreamFrame{
			Type:      "complete",
			Affected:  rows.Affected(),
			Truncated: truncated,
			ElapsedMS: time.Since(started).Milliseconds(),
			RowCount:  rowCount,
		})
	}

	for rows.Next() {
		if err := ctx.Err(); err != nil {
			cancel()
			return nerr.Wrap(nerr.Canceled, "studio.Stream", "query canceled", err)
		}
		if rowCount >= MaxResultRows {
			cancel()
			_ = closeRows()
			return complete(true)
		}

		vals := rows.Values()
		if len(vals) != len(columns) {
			cancel()
			return nerr.New(nerr.InvalidFormat, "studio.Stream", "row width does not match result columns")
		}
		rec := make([]*string, len(vals))
		rowBytes := 0
		for i, v := range vals {
			if v.Null {
				continue
			}
			str := v.String()
			rowBytes += len(str)
			if rowBytes > StreamRowBytes || used+rowBytes > MaxResultBytes {
				cancel()
				_ = closeRows()
				return complete(true)
			}
			rec[i] = &str
		}
		used += rowBytes
		rowCount++
		if len(batch) > 0 && batchBytes+rowBytes > StreamBatchBytes {
			if err := flush(); err != nil {
				return err
			}
		}
		batchBytes += rowBytes
		batch = append(batch, rec)
		if len(batch) >= StreamBatchRows || batchBytes >= StreamBatchBytes {
			if err := flush(); err != nil {
				return err
			}
		}
	}
	if err := rows.Err(); err != nil {
		return err
	}
	if err := closeRows(); err != nil {
		return err
	}
	return complete(false)
}

func typeNames(in []types.Type) []string {
	out := make([]string, len(in))
	for i := range in {
		out[i] = in[i].String()
	}
	return out
}

func resultMetadataBytes(r ResultSet) int {
	n := 0
	for _, col := range r.Columns {
		n += len(col)
	}
	for _, typ := range r.ColumnTypes {
		n += len(typ)
	}
	return n
}
