// Official TypeScript entry for the Deno driver. Speaks NSQL v1.
// Encryption keys and passwords are never accepted in a URL.

export {
  Kind,
  NextSQLError,
  ReadConsistency,
  Type,
  connect,
  connectCluster,
  decodeDecimal,
  decodeHelloOK,
  decodeNSJB,
  decodeNodeStatus,
  decodeValue,
  encodeDecimalString,
  encodeHello,
  encodeParam,
  encodeSetReadConsistency,
  formatUUID,
  isLoopback,
  isReadOnlySQL,
  txnControl,
  validateConfig,
  FieldType,
  MemoryFieldKeyring,
  FileFieldKeyring,
  decryptField,
  encryptField,
  generateFieldKey,
  inspectField,
} from './mod.js';

export type {
  Box,
  Cluster,
  Column,
  Config,
  Conn,
  DecodeValue,
  ExecResult,
  Hello,
  HelloOK,
  LineString,
  NodeStatus,
  Param,
  Point,
  Polygon,
  ReadConsistencyMode,
  Rows,
  Stmt,
  TLSOptions,
  Value,
  VectorRef,
  SparseVector,
  FieldKey,
  FieldKeyProvider,
  FieldKeyInfo,
  FieldTypeDescriptor,
} from '../js/types.d.ts';
