#!/usr/bin/env bash
# Build NextSQL Linux installers: tarball, self-extracting .run, .deb, and RPM if rpmbuild exists.
#
# Usage:
#   scripts/build-linux-installer.sh
#   scripts/build-linux-installer.sh --arch amd64,arm64 --out dist
set -euo pipefail

ROOT="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
# shellcheck source=../packaging/lib.sh
. "$ROOT/packaging/lib.sh"
require_repo_root
need_cmd go
need_cmd tar
need_cmd gzip
need_cmd sha256sum

ARCHES=""
DIST="$ROOT/dist"
SKIP_DEB=0
SKIP_TARBALL=0
SKIP_RUN=0
SKIP_RPM=0
NAME="nextsql"

usage() {
	cat <<EOF
Usage: $(basename "$0") [options]

  --arch LIST     Go arches (comma-separated, or 'all' for amd64,arm64).
                  Default: host GOARCH ($(go env GOARCH)).
  --out DIR       Output directory (default: dist/).
  --skip-deb      Do not build .deb packages.
  --skip-tarball  Do not build .tar.gz archives.
  --skip-run      Do not build self-extracting .run installers.
  --skip-rpm      Do not build .rpm even if rpmbuild is present.
  -h, --help      Show this help.

$(usage_common)
EOF
}

while [ $# -gt 0 ]; do
	case "$1" in
	-h|--help) usage; exit 0 ;;
	--arch) ARCHES="${2:?}"; shift ;;
	--arch=*) ARCHES="${1#--arch=}" ;;
	--out) DIST="${2:?}"; shift ;;
	--out=*) DIST="${1#--out=}" ;;
	--skip-deb) SKIP_DEB=1 ;;
	--skip-tarball) SKIP_TARBALL=1 ;;
	--skip-run) SKIP_RUN=1 ;;
	--skip-rpm) SKIP_RPM=1 ;;
	*) die "unknown argument: $1" ;;
	esac
	shift
done

if [ -z "$ARCHES" ]; then
	ARCHES="$(default_go_arches linux)"
fi
ARCHES="$(parse_arches "$ARCHES")"

VERSION="$(version_string)"
DEB_VER="$(deb_version "$VERSION")"
FVER="$(file_version "$VERSION")"
STAGE="$DIST/.linux-stage"
PKG="$ROOT/packaging"
mkdir -p "$DIST"
rm -rf "$STAGE"
mkdir -p "$STAGE"

info "NextSQL $VERSION  linux installers  arches: $ARCHES"

stage_bins() {
	local arch="$1" dest="$2"
	local cache="$STAGE/bins-${arch}"
	if [ ! -x "$cache/nextsql" ]; then
		mkdir -p "$cache"
		build_go linux "$arch" "$cache/nextsql"       "$ROOT/cmd/nextsql"
		build_go linux "$arch" "$cache/nextsqld"      "$ROOT/cmd/nextsqld"
		build_go linux "$arch" "$cache/nextsql-bench" "$ROOT/cmd/nextsql-bench"
	fi
	mkdir -p "$dest"
	cp "$cache/nextsql" "$cache/nextsqld" "$cache/nextsql-bench" "$dest/"
	chmod 0755 "$dest/nextsql" "$dest/nextsqld" "$dest/nextsql-bench"
}

write_tarball_tree() {
	local arch="$1" dest="$2"
	rm -rf "$dest"
	mkdir -p "$dest/bin" "$dest/etc" "$dest/systemd"
	stage_bins "$arch" "$dest/bin"
	cp "$PKG/linux/nextsql.conf" "$dest/etc/nextsql.conf"
	cp "$PKG/linux/nextsql.service" "$dest/systemd/nextsql.service"
	cp "$PKG/linux/nextsql.user.service" "$dest/systemd/nextsql.user.service"
	cp "$PKG/linux/nextsql.sysusers" "$dest/systemd/nextsql.sysusers"
	cp "$PKG/linux/nextsql.tmpfiles" "$dest/systemd/nextsql.tmpfiles"
	install -m 0755 "$PKG/linux/tarball/install.sh" "$dest/install.sh"
	install -m 0755 "$PKG/linux/tarball/uninstall.sh" "$dest/uninstall.sh"
	cp "$PKG/linux/tarball/README" "$dest/README"
	cp "$PKG/COPYRIGHT" "$dest/COPYRIGHT"
	printf '%s\n' "$VERSION" >"$dest/VERSION"
}

build_tarball() {
	local arch="$1"
	local dir="$STAGE/nextsql-${FVER}-linux-${arch}"
	write_tarball_tree "$arch" "$dir"
	local out="$DIST/nextsql-${FVER}-linux-${arch}.tar.gz"
	info "tarball $out"
	tar -C "$STAGE" -czf "$out" "$(basename "$dir")"
	printf '%s\n' "$out"
}

build_run() {
	local arch="$1"
	local dir="$STAGE/nextsql-${FVER}-linux-${arch}"
	if [ ! -d "$dir" ]; then
		write_tarball_tree "$arch" "$dir"
	fi
	local payload="$STAGE/payload-${arch}.tar.gz"
	tar -C "$dir" -czf "$payload" .
	local out="$DIST/nextsql-${FVER}-linux-${arch}.run"
	info "self-extracting installer $out"
	{
		cat <<'STUB'
#!/bin/sh
# NextSQL self-extracting installer. Generated by scripts/build-linux-installer.sh.
set -eu
TMP="$(mktemp -d "${TMPDIR:-/tmp}/nextsql-install.XXXXXX")"
cleanup() { rm -rf "$TMP"; }
trap cleanup EXIT INT HUP
ARCHIVE_LINE="$(awk '/^#__NEXTSQL_PAYLOAD__$/ { print NR + 1; exit }' "$0")"
[ -n "$ARCHIVE_LINE" ] || { echo "corrupt installer: missing payload marker" >&2; exit 1; }
tail -n +"$ARCHIVE_LINE" "$0" | gzip -dc | tar -xf - -C "$TMP"
if [ ! -x "$TMP/install.sh" ]; then
	echo "corrupt installer: missing install.sh" >&2
	exit 1
fi
"$TMP/install.sh" "$@"
status=$?
exit "$status"
#__NEXTSQL_PAYLOAD__
STUB
		# payload is already gzip-compressed; the stub runs gzip -dc.
		# Re-wrap: we tar'd with -czf so it IS gzip. The stub pipes gzip -dc | tar -xf.
		# That matches. Append the gzip stream as-is.
		cat "$payload"
	} >"$out"
	chmod 0755 "$out"
	printf '%s\n' "$out"
}

write_deb_tree() {
	local arch="$1" dest="$2"
	local debarch
	debarch="$(goarch_to_deb "$arch")"
	rm -rf "$dest"
	mkdir -p \
		"$dest/usr/bin" \
		"$dest/etc/nextsql" \
		"$dest/lib/systemd/system" \
		"$dest/usr/lib/sysusers.d" \
		"$dest/usr/lib/tmpfiles.d" \
		"$dest/usr/share/doc/nextsql" \
		"$dest/DEBIAN"
	stage_bins "$arch" "$dest/usr/bin"
	chmod 0755 "$dest/usr/bin/"*
	install -m 0640 "$PKG/linux/nextsql.conf" "$dest/etc/nextsql/nextsql.conf"
	install -m 0644 "$PKG/linux/nextsql.service" "$dest/lib/systemd/system/nextsql.service"
	install -m 0644 "$PKG/linux/nextsql.sysusers" "$dest/usr/lib/sysusers.d/nextsql.conf"
	install -m 0644 "$PKG/linux/nextsql.tmpfiles" "$dest/usr/lib/tmpfiles.d/nextsql.conf"
	install -m 0644 "$PKG/linux/tarball/README" "$dest/usr/share/doc/nextsql/README"
	install -m 0644 "$PKG/COPYRIGHT" "$dest/usr/share/doc/nextsql/copyright"
	gzip -9 -c "$ROOT/USAGE.md" >"$dest/usr/share/doc/nextsql/USAGE.md.gz" 2>/dev/null || true
	printf '%s\n' "$VERSION" >"$dest/usr/share/doc/nextsql/VERSION"
	install -m 0755 "$PKG/linux/debian/postinst" "$dest/DEBIAN/postinst"
	install -m 0755 "$PKG/linux/debian/prerm" "$dest/DEBIAN/prerm"
	install -m 0755 "$PKG/linux/debian/postrm" "$dest/DEBIAN/postrm"
	install -m 0644 "$PKG/linux/debian/conffiles" "$dest/DEBIAN/conffiles"
	local size
	size="$(du -sk --exclude=DEBIAN "$dest" | awk '{print $1}')"
	cat >"$dest/DEBIAN/control" <<EOF
Package: ${NAME}
Version: ${DEB_VER}
Section: database
Priority: optional
Architecture: ${debarch}
Maintainer: NextSQL <nextsql@bzync>
Homepage: https://github.com/bzync/nextsql
Installed-Size: ${size}
Recommends: systemd
Description: Encrypted-by-default multimodel database
 NextSQL is a high-performance, encrypted-by-default multimodel database.
 Relational SQL, native JSON, vector search, full-text search, and
 geospatial types share one ACID engine, one WAL, and one query optimizer.
 Native NSQL v1 protocol on port 7210. This package ships nextsql,
 nextsqld, and nextsql-bench. The service is not started until you
 initialize a data directory.
EOF
}

build_deb() {
	local arch="$1"
	need_cmd dpkg-deb
	local tree="$STAGE/deb-${arch}"
	write_deb_tree "$arch" "$tree"
	local debarch
	debarch="$(goarch_to_deb "$arch")"
	local out="$DIST/${NAME}_${FVER}_${debarch}.deb"
	info "deb $out"
	if command -v fakeroot >/dev/null 2>&1; then
		fakeroot dpkg-deb --root-owner-group --build "$tree" "$out" >/dev/null
	else
		dpkg-deb --root-owner-group --build "$tree" "$out" >/dev/null
	fi
	printf '%s\n' "$out"
}

build_rpm() {
	local arch="$1"
	command -v rpmbuild >/dev/null 2>&1 || return 0
	local rpmarch
	rpmarch="$(goarch_to_rpm "$arch")"
	local rpmver
	rpmver="$(printf '%s\n' "$VERSION" | tr '-' '_')"
	local tree="$STAGE/rpm-${arch}"
	# Reuse debian filesystem layout minus DEBIAN/.
	write_deb_tree "$arch" "$tree"
	rm -rf "$tree/DEBIAN"
	# RPM expects /usr/lib/systemd/system not /lib/systemd/system on some distros.
	mkdir -p "$tree/usr/lib/systemd/system"
	if [ -f "$tree/lib/systemd/system/nextsql.service" ]; then
		mv "$tree/lib/systemd/system/nextsql.service" "$tree/usr/lib/systemd/system/"
		rmdir "$tree/lib/systemd/system" 2>/dev/null || true
		rmdir "$tree/lib/systemd" 2>/dev/null || true
		rmdir "$tree/lib" 2>/dev/null || true
	fi
	local spec="$STAGE/nextsql-${arch}.spec"
	sed \
		-e "s|@@RPM_VERSION@@|$rpmver|g" \
		-e "s|@@RPM_ARCH@@|$rpmarch|g" \
		-e "s|@@STAGE@@|$tree|g" \
		"$PKG/linux/nextsql.spec.in" >"$spec"
	local rpmdir="$STAGE/rpmbuild-${arch}"
	mkdir -p "$rpmdir"/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
	info "rpm nextsql-${rpmver}-1.${rpmarch}.rpm"
	if ! rpmbuild -bb --define "_topdir $rpmdir" --define "_build_id_links none" \
		--target "$rpmarch" "$spec" >/dev/null; then
		log "warning: rpmbuild failed for $arch (skipping)"
		return 0
	fi
	find "$rpmdir/RPMS" -name '*.rpm' -exec cp {} "$DIST/" \;
}

ARTIFACTS=()
for arch in $ARCHES; do
	case "$arch" in
	amd64|arm64|386|arm) ;;
	*) die "unsupported linux arch: $arch" ;;
	esac
	add_artifact() {
		local f="$1"
		[ -n "$f" ] && [ -f "$f" ] || die "build produced no file: ${f:-<empty>}"
		ARTIFACTS+=("$f")
	}
	if [ "$SKIP_TARBALL" -eq 0 ]; then
		add_artifact "$(build_tarball "$arch")"
	fi
	if [ "$SKIP_RUN" -eq 0 ]; then
		add_artifact "$(build_run "$arch")"
	fi
	if [ "$SKIP_DEB" -eq 0 ]; then
		if command -v dpkg-deb >/dev/null 2>&1; then
			add_artifact "$(build_deb "$arch")"
		else
			log "warning: dpkg-deb not found; skipping .deb for $arch"
		fi
	fi
	if [ "$SKIP_RPM" -eq 0 ]; then
		build_rpm "$arch" || true
	fi
done

# Collect any rpms that landed in DIST.
shopt -s nullglob
for f in "$DIST"/*.rpm; do
	ARTIFACTS+=("$f")
done
shopt -u nullglob

info "checksums"
(
	cd "$DIST"
	shopt -s nullglob
	: >SHA256SUMS.linux
	for f in nextsql-*-linux-*.tar.gz nextsql-*-linux-*.run nextsql_*_*.deb nextsql-*.rpm; do
		sha256sum "$f" >>SHA256SUMS.linux
	done
)

info "Linux installers"
printf '    %s\n' "${ARTIFACTS[@]}"
info "SHA256SUMS.linux -> $DIST/SHA256SUMS.linux"
rm -rf "$STAGE"
