#!/usr/bin/env bash
# Cut a retained upgrade fixture from a RELEASED NextSQL build.
#
# A fixture is a real data directory — pages, WAL, UNDO, keystore, auth and ACL
# sidecars — produced by the binaries of one release, together with the query
# results and the compatibility catalog that release itself reported. Later
# releases replay it in tests/upgrade: the archive is the only thing that can
# prove a format change does not strand data written by a shipped binary, so it
# must be generated by the shipped binary and then never edited by hand.
#
# Cut one per release, on the release commit, and commit the archives:
#
#   git worktree add /tmp/rel v1.2.3
#   (cd /tmp/rel && go build -o /tmp/relbin/nextsql ./cmd/nextsql \
#                  && go build -o /tmp/relbin/nextsqld ./cmd/nextsqld)
#   scripts/make-upgrade-fixture.sh --label v1.2.3 --bindir /tmp/relbin
#
# Produces <out>/<label>-clean.tar.gz (cleanly shut down) and
# <out>/<label>-dirty.tar.gz (SIGKILLed with committed work still in the WAL,
# so the next release's recovery is exercised, not just its page reader).
#
# The key file and password in a fixture are generated for that fixture and are
# test material only: they unlock nothing but the archive they ship in.
set -euo pipefail

label=""
bindir=""
out="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/tests/upgrade/testdata"
port=7311
data_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/tests/upgrade/testdata"

die() { echo "make-upgrade-fixture: $*" >&2; exit 1; }

while [ $# -gt 0 ]; do
	case "$1" in
	--label) label="${2:-}"; shift 2 ;;
	--bindir) bindir="${2:-}"; shift 2 ;;
	--out) out="${2:-}"; shift 2 ;;
	--port) port="${2:-}"; shift 2 ;;
	-h|--help) sed -n '2,25p' "$0"; exit 0 ;;
	*) die "unknown argument $1" ;;
	esac
done

[ -n "$label" ] || die "--label <release> is required (e.g. v0.0.1)"
[ -n "$bindir" ] || die "--bindir <dir containing nextsql and nextsqld> is required"
nextsql="$bindir/nextsql"
nextsqld="$bindir/nextsqld"
[ -x "$nextsql" ] || die "$nextsql is not executable"
[ -x "$nextsqld" ] || die "$nextsqld is not executable"

here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
corpus="$data_root/fixture.sql"
queries="$data_root/queries.sql"
dirty_corpus="$data_root/dirty.sql"
dirty_queries="$data_root/dirty-queries.sql"
for f in "$corpus" "$queries" "$dirty_corpus" "$dirty_queries"; do
	[ -f "$f" ] || die "missing $f"
done
mkdir -p "$out"

work="$(mktemp -d)"
server_pid=""
cleanup() {
	if [ -n "$server_pid" ] && kill -0 "$server_pid" 2>/dev/null; then
		kill -9 "$server_pid" 2>/dev/null || true
	fi
	rm -rf "$work"
}
trap cleanup EXIT

# strip_sql prints the executable statements of a corpus file: one per line,
# comments and blank lines removed.
strip_sql() { grep -vE '^[[:space:]]*(--.*)?$' "$1"; }

exec_sql() { # exec_sql <workdir> <sql> [extra flags...]
	local w="$1" sql="$2"; shift 2
	"$nextsql" exec --addr "127.0.0.1:$port" --user app --password-file "$w/password" \
		--insecure --no-env "$@" -c "$sql"
}

start_server() { # start_server <workdir>
	local w="$1"
	"$nextsqld" --data-dir "$w/data" --key-file "$w/root.key" \
		--listen "127.0.0.1:$port" --user app --password-file "$w/password" \
		--no-env >"$w/server.log" 2>&1 &
	server_pid=$!
	local i
	for i in $(seq 1 100); do
		if exec_sql "$w" "SELECT 1" >/dev/null 2>&1; then return 0; fi
		kill -0 "$server_pid" 2>/dev/null || { cat "$w/server.log" >&2; die "server exited during startup"; }
		sleep 0.2
	done
	cat "$w/server.log" >&2
	die "server did not become ready on 127.0.0.1:$port"
}

run_corpus() { # run_corpus <workdir> <file>
	local w="$1" f="$2" stmt
	while IFS= read -r stmt; do
		exec_sql "$w" "$stmt" >/dev/null || die "statement failed against $label: $stmt"
	done < <(strip_sql "$f")
}

record_queries() { # record_queries <workdir> <file> ... ; appends to $w/expected.jsonl
	local w="$1"; shift
	local f stmt json
	for f in "$@"; do
		while IFS= read -r stmt; do
			json="$(exec_sql "$w" "$stmt" --json)" || die "query failed against $label: $stmt"
			# One JSON object per line: {"sql":…,"result":…}. jq is not assumed.
			printf '%s\t%s\n' "$stmt" "$json" >> "$w/expected.jsonl"
		done < <(strip_sql "$f")
	done
}

build_fixture() { # build_fixture <kind: clean|dirty>
	local kind="$1"
	local w="$work/$kind"
	mkdir -p "$w"
	printf 'fixture-only-password-0\n' > "$w/password"
	chmod 600 "$w/password"
	: > "$w/expected.jsonl"

	"$nextsql" init --data-dir "$w/data" --key-file "$w/root.key" \
		--user app --password-file "$w/password" --no-env > "$w/init.log" 2>&1 \
		|| { cat "$w/init.log" >&2; die "init failed"; }

	start_server "$w"
	run_corpus "$w" "$corpus"
	if [ "$kind" = dirty ]; then
		run_corpus "$w" "$dirty_corpus"
		record_queries "$w" "$queries" "$dirty_queries"
	else
		record_queries "$w" "$queries"
	fi

	if [ "$kind" = dirty ]; then
		# Committed work is acknowledged; take the process out without a clean
		# close so the archive's WAL still has redo to replay.
		kill -9 "$server_pid"; wait "$server_pid" 2>/dev/null || true; server_pid=""
	else
		kill -TERM "$server_pid"; wait "$server_pid" 2>/dev/null || true; server_pid=""
	fi

	# The generating release's own view of the archive: its compatibility
	# catalog (what it can read) and the on-disk versions it actually wrote.
	# tests/upgrade parses this, so rollback preservation is checked against
	# recorded evidence rather than an assumption about the old binary.
	"$nextsql" diagnose --data-dir "$w/data" > "$w/diagnose.txt" 2>&1 || true

	local version
	version="$("$nextsql" version 2>/dev/null | head -1)"
	{
		printf '{\n'
		printf '  "label": "%s",\n' "$label"
		printf '  "kind": "%s",\n' "$kind"
		printf '  "generator_version": "%s",\n' "${version//\"/\\\"}"
		printf '  "created": "%s",\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
		printf '  "data_dir": "data",\n'
		printf '  "key_file": "root.key",\n'
		printf '  "instance_key_file": "root.key.instance",\n'
		printf '  "password_file": "password",\n'
		printf '  "user": "app"\n'
		printf '}\n'
	} > "$w/manifest.json"

	rm -f "$w/init.log" "$w/server.log"
	local archive="$out/$label-$kind.tar.gz"
	tar --sort=name --owner=0 --group=0 --numeric-owner \
		--mtime="1970-01-01 00:00:00Z" \
		-C "$w" -czf "$archive" .
	echo "wrote $archive ($(du -h "$archive" | cut -f1))"
}

build_fixture clean
build_fixture dirty
